# Generated by Django 4.2.8 on 2023-12-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gardu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gardu_name', models.CharField(max_length=100)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rc_status', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('up3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Rtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_rtu', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_rtu', models.CharField(blank=True, max_length=50, null=True)),
                ('model_rtu', models.CharField(blank=True, max_length=50, null=True)),
                ('rtu_status', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('gardu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.gardu')),
            ],
        ),
        migrations.CreateModel(
            name='Rectifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_recti', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_recti', models.CharField(blank=True, max_length=50, null=True)),
                ('model_recti', models.CharField(blank=True, max_length=50, null=True)),
                ('recti_status', models.BooleanField(default=False)),
                ('brand_baterai', models.CharField(blank=True, max_length=50, null=True)),
                ('type_baterai', models.CharField(blank=True, max_length=50, null=True)),
                ('jumlah_baterai', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('gardu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.gardu')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_media', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_media', models.CharField(blank=True, max_length=50, null=True)),
                ('model_media', models.CharField(blank=True, max_length=50, null=True)),
                ('media_status', models.BooleanField(default=False)),
                ('protokol', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('gardu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.gardu')),
            ],
        ),
        migrations.CreateModel(
            name='FaultIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_fi', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_fi', models.CharField(blank=True, max_length=50, null=True)),
                ('model_fi', models.CharField(blank=True, max_length=50, null=True)),
                ('fi_status', models.BooleanField(default=False)),
                ('brand_ct', models.CharField(blank=True, max_length=50, null=True)),
                ('model_ct', models.CharField(blank=True, max_length=50, null=True)),
                ('ct_status', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('gardu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.gardu')),
            ],
        ),
    ]
