# Generated by Django 4.2.8 on 2023-12-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_gardu_lat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Up3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up3', models.CharField(blank=True, max_length=50, null=True)),
                ('wilayah_kerja', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
