# Generated by Django 4.2.8 on 2023-12-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_gardu_up3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='up3',
            options={'verbose_name': 'UP3', 'verbose_name_plural': 'UP3'},
        ),
    ]
