# Generated by Django 4.2.8 on 2023-12-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_up3_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardu',
            name='up3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.up3'),
        ),
    ]
