# Generated by Django 4.2.8 on 2023-12-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_gardu_up3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardu',
            name='up3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.up3'),
        ),
        migrations.AlterField(
            model_name='up3',
            name='up3',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
